name: Daily Green

on:
  schedule:
    - cron: '0 12 * * *'
  workflow_dispatch:

jobs:
  commit:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v3

      - name: Make a daily commit
        env:
          NOREPLY_EMAIL: ${{ secrets.NOREPLY_EMAIL }}
          GH_USERNAME: ${{ secrets.GH_USERNAME }}
        run: |
          git config user.email "$NOREPLY_EMAIL"
          git config user.name "$GH_USERNAME"
          echo "$(date)" >> log.txt
          git add .
          git commit -m "daily update $(date)" || echo "no changes to commit"
          git push
